# Generated by Django 2.1.3 on 2018-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181105_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
